wandb_version: 1

bert_model:
  desc: null
  value: bert-base-uncased
lr:
  desc: null
  value: 0.0001
runs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 100
clip:
  desc: null
  value: 5
patience:
  desc: null
  value: 5
bidirectionality:
  desc: null
  value: false
dropout_layer:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
architecture:
  desc: null
  value: bert
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: ATIS
optimizer:
  desc: null
  value: AdamW
loss_slots:
  desc: null
  value: CrossEntropyLoss
loss_intents:
  desc: null
  value: CrossEntropyLoss
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.38.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729152603
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.17.5
      6: 4.38.0
      8:
      - 5
      13: linux-x86_64
