_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 256
clip:
    value: 5
dataset:
    value: PTB
device:
    value: cuda:0
emb_size:
    value: 300
epochs:
    value: 200
hid_size:
    value: 200
loss:
    value: CrossEntropyLoss
lr:
    value: 1
metric:
    value: Perplexity
model:
    value: LSMT
optimizer:
    value: SGD
patience:
    value: 3
runs:
    value: 1
var_dropout:
    value: false
weight_tying:
    value: true
