wandb_version: 1

lr:
  desc: null
  value: 3
runs:
  desc: null
  value: 1
hid_size:
  desc: null
  value: 300
emb_size:
  desc: null
  value: 300
epochs:
  desc: null
  value: 200
clip:
  desc: null
  value: 5
patience:
  desc: null
  value: 5
device:
  desc: null
  value: cuda:0
model:
  desc: null
  value: LSMT
optimizer:
  desc: null
  value: NTAvSGD
weight_tying:
  desc: null
  value: true
var_dropout:
  desc: null
  value: true
loss:
  desc: null
  value: CrossEntropyLoss
metric:
  desc: null
  value: Perplexity
dataset:
  desc: null
  value: PTB
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729665069
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
