wandb_version: 1

lr:
  desc: null
  value: 1.5
model:
  desc: null
  value: LM_RNN
optimizer:
  desc: null
  value: SGD
epochs:
  desc: null
  value: 100
patience:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.38.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721750003
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.17.5
      6: 4.38.0
      8:
      - 5
      13: linux-x86_64
